- name: Update nginx configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  become: yes

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: Set firewall rules (allow http, https and ssh connections)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  with_items:
    - http
    - https
    - ssh
  become: yes
