---

- name: Ensure airflow directory exists
  ansible.builtin.file:
    path: "{{ airflow_directory }}"
    state: directory

- name: Ensure dags, logs and plugins folders exist
  ansible.builtin.file:
    path: "{{ airflow_directory }}/{{ item }}"
    state: directory
  with_items:
    - dags
    - logs
    - plugins

- name: Update Airflow configuration
  template:
    src: airflow.cfg.j2
    dest: "/home/{{ ansible_user }}/airflow/airflow.cfg"
