- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack Shade modules run by Shade on your local machine.

  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances

  vars:
    security_group_rules:
      - name: ssh
        protocol: tcp
        port: 22
        allowed_ips:
          - "193.166.1.0/24" #CSC Office
          - "193.166.2.0/24" #CSC Office
          - "193.166.84.0/24" #CSC VPN
          - "193.166.85.0/24" #CSC VPN

      - name: http
        protocol: tcp
        port: 80
        allowed_ips:
          - "193.166.1.0/24" #CSC Office
          - "193.166.2.0/24" #CSC Office
          - "193.166.84.0/24" #CSC VPN
          - "193.166.85.0/24" #CSC VPN

- name: Setup Puhti access for Airflow and install remote scripts
  hosts: puhti
  roles:
    - public-key-to-puhti
    - restic-script-to-puhti

- name: Install requirements for Airflow
  hosts: airflow
  roles:
    - airflow-requirements
    - airflow-config
    - airflow-db
    - nginx-setup
    - harvester-setup
    - airflow-systemd-service
    - disable-reboot
