# Unit tests for a Python project with Makefile taking care of installing requirements


name: Python unit tests

on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      run: |
        yum install python3 pip3 -y
        pip3 install -r requirements_dev.txt
    - name: Test with pytest
      run: python3 -m pytest
