name: Python unit tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: get constraints file for Airflow
      run: make constraints.txt
    - name: Install required Python packages
      run: pip3 install -r requirements_dev.txt --user -c constraints.txt
    - name: Test with pytest
      run: python3.8 -m pytest
